[package]
name = "f1-telemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rdkafka = { version = "0.38", features = ["cmake-build"] }
tokio = { version = "1.47", features = ["full"] }
