services:
  controller:
    image: apache/kafka:latest
    container_name: controller
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092" # TODO
    depends_on:
      - controller
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "broker:9092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka-init:
    image: apache/kafka:latest
    depends_on:
      broker:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      until /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list; do
        echo 'waiting for Kafka to be ready...'
        sleep 2
      done

      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic f1-telemetry-lap --replication-factor 1 --partitions 2
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic f1-telemetry-car-telemetry --replication-factor 1 --partitions 2
      "

  f1-telemetry:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      - RUST_LOG=info
      - UDP_URL=0.0.0.0
      - UDP_PORT=20777
      - KAFKA_BOOTSTRAP_SERVERS=broker:19092
      - LAP_TOPIC=f1-telemetry-lap
      - CAR_TELEMETRY_TOPIC=f1-telemetry-car-telemetry
