scalaVersion := "2.12.18"
name := "consumer"
organization := "cc.phish3y.consumer"
version := "1.0"

libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.3.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.5.6" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.5.6" % "provided"
libraryDependencies += "org.apache.iceberg" %% "iceberg-spark-runtime-3.5" % "1.10.0" % "provided"
libraryDependencies += "io.opentelemetry" % "opentelemetry-api" % "1.46.0"
